### PR TITLE
replace from old repo to new

### LINKED ISSUE #74: [Epic] Token overview and creation
# Why
The main functionalities are not working correctly, but a discussion on the value of this feature is still required.

### PR DESCRIPTION
**Pull request by DevArtemNuss**
# Description

Fixes #74
remove infinity loop for get table row and duplicates

## Screenshots
Снимок экрана 2022-08-25 в 14 58 29

# How Has This Been Tested?

We go to the ballots page and scroll down and see the loading of elements without duplicates

### CODE REVIEW

File: src/pages/trails/ballots/list/ballots-list.vue [hunk 1]
```diff
@@ -1,242 +1,209 @@
...
-import BallotListItem from "../components/ballot-list-item";
-import BallotView from "../view/ballot-view";
-import WelcomeCard from "../../../../components/welcome-card";
-import ActionBar from "../../../../components/action-bar";
+import { mapActions, mapGetters, mapMutations } from 'vuex'
+import BallotForm from '../components/ballot-form'
+import BallotListItem from '../components/ballot-list-item'
+import BallotView from '../view/ballot-view'
+import WelcomeCard from '../../../../components/welcome-card'
+import ActionBar from '../../../../components/action-bar'
```
Comment (donnyquixotic) [inline src/pages/trails/ballots/list/ballots-list.vue:7]: there is an alias, `~` for `src` e.g.  ~/components/action-bar` use that instead of relative path.

**Review by donnyquixotic — CHANGES_REQUESTED** [review]

File: src/pages/trails/ballots/list/ballots-list.vue (hunk 1 above)
Comment (DevArtemNuss) [reply src/pages/trails/ballots/list/ballots-list.vue:7]: App •  ERROR  •  UI  in ./src/pages/trails/ballots/list/ballots-list.vue?vue&type=script&lang=js

Module not found: Can't resolve imported dependency "~/view/ballot-view"
Did you forget to install it? You can run: yarn add ~/view/ballot-view

**Review by donnyquixotic — APPROVED** [review]
