### PR TITLE
Bug/fix infinity scrool init0pos

### LINKED ISSUE #67: Infinite scroll requires scroll to show first results
**Describe the bug**
When reaching the ballots page, you can see the three dots indicating a request is being made, and it stops after a few seconds. If you don't scroll down on the page, the ballots don't show.

**To Reproduce**
1. Go to the ballots page
2. Don't click on anything or scroll
3. See the three dots being animated
4. See the three dots disappearing
5. No ballot is shown

**Expected behavior**
Active ballots from the VOTE treasury should be listed

**Screenshots**
Screen Shot 2022-09-13 at 20 09 06

### LINKED ISSUE #69: account list cut off on expand
**Describe the bug**
expanding the account list is cut off (can't scroll through list)

**To Reproduce**
1. Go to https://app.telos.net/trails/ballots/hire.lobby3/1663166808123
2. Click on '>' to the right of 'number of accounts' to expand list
4. See cut off list

**Expected behavior**
should be able to scroll through the entire list of accounts

**Screenshots**
image

### PR DESCRIPTION
**Pull request by DevArtemNuss**
# Description

Fixes #67,  #75
expanding the account list is cut off (can't scroll through list)

## Changes

Change conditions

# Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have executed manual tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/pages/trails/ballots/list/BallotsList.vue [hunk 1]
```diff
@@ -82,7 +82,12 @@ export default {
         status === true
       ) {
         this.$refs.infiniteScroll.resume();
-        this.limit += 45;
+        // Start allways with a limit of 200 and then go +100 on next query
+        if (status === true) {
```
Comment (karynemayer) [inline src/pages/trails/ballots/list/BallotsList.vue:86]: To me is not clear when the `status` would not be true since we're calling `this.onLoad(true)` everywhere on this page 🤔  Would you mind helping me out understanding?

**Comment by karynemayer** [comment]
@DevArtemNuss I think the issue this PR is associated with is not correct, which took me some time to see 😅 I think it is the #67 and not the #69

File: src/pages/trails/ballots/list/BallotsList.vue (hunk 1 above)
Comment (DevArtemNuss) [reply src/pages/trails/ballots/list/BallotsList.vue]: I renamed this, but this logic for filters, when we change filter we must reset out limit and positions for load

**Comment by DevArtemNuss** [comment]
> 
Yeah )) sorry, i change this to #67

**Review by karynemayer — APPROVED** [review]
